// <auto-generated />
using System;
using MagicVillaAPI.EntityContext.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(CommonDBContext))]
    [Migration("20240228151101_villa_numbers_table")]
    partial class villa_numbers_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MagicVillaAPI.Models.DAO.Villa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedDateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef463a38-fa6d-4ff7-b8a4-ba4fb65ca56c"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 20:41:01",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa3.jpg",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Rate = 200,
                            Sqft = 550,
                            UpdatedDateTime = "28-02-2024 20:41:01"
                        },
                        new
                        {
                            Id = new Guid("ce9c324d-419d-4525-9e14-862f921d1f04"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 20:41:01",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa1.jpg",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Rate = 300,
                            Sqft = 550,
                            UpdatedDateTime = "28-02-2024 20:41:01"
                        },
                        new
                        {
                            Id = new Guid("7c6d56ad-5f5f-4210-808a-47099cbf6c81"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 20:41:01",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa4.jpg",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Rate = 400,
                            Sqft = 750,
                            UpdatedDateTime = "28-02-2024 20:41:01"
                        },
                        new
                        {
                            Id = new Guid("c7e8eba4-196c-4598-95ad-cab683a63620"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 20:41:01",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa5.jpg",
                            Name = "Diamond Villa",
                            Occupancy = 4,
                            Rate = 550,
                            Sqft = 900,
                            UpdatedDateTime = "28-02-2024 20:41:01"
                        },
                        new
                        {
                            Id = new Guid("f216ff5a-4b8e-4869-9ab2-6ee08675158c"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 20:41:01",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa2.jpg",
                            Name = "Diamond Pool Villa",
                            Occupancy = 4,
                            Rate = 600,
                            Sqft = 1100,
                            UpdatedDateTime = "28-02-2024 20:41:01"
                        });
                });

            modelBuilder.Entity("MagicVillaAPI.Models.DAO.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedDateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VillaNo");

                    b.ToTable("villa_numbers");
                });
#pragma warning restore 612, 618
        }
    }
}
