// <auto-generated />
using System;
using MagicVillaAPI.EntityContext.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(CommonDBContext))]
    [Migration("20240228182734_villaforeignkey")]
    partial class villaforeignkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MagicVillaAPI.Models.DAO.Villa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedDateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("048ea2b2-5bd2-4537-b098-11034e29693e"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 23:57:34",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa3.jpg",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Rate = 200,
                            Sqft = 550,
                            UpdatedDateTime = "28-02-2024 23:57:34"
                        },
                        new
                        {
                            Id = new Guid("bd4bdc2f-07b1-4207-a070-5e94ba331abc"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 23:57:34",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa1.jpg",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Rate = 300,
                            Sqft = 550,
                            UpdatedDateTime = "28-02-2024 23:57:34"
                        },
                        new
                        {
                            Id = new Guid("1527385c-290d-4635-9216-52b18704bdb8"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 23:57:34",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa4.jpg",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Rate = 400,
                            Sqft = 750,
                            UpdatedDateTime = "28-02-2024 23:57:34"
                        },
                        new
                        {
                            Id = new Guid("279b0ce2-0166-4845-9231-6250e98dffb9"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 23:57:34",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa5.jpg",
                            Name = "Diamond Villa",
                            Occupancy = 4,
                            Rate = 550,
                            Sqft = 900,
                            UpdatedDateTime = "28-02-2024 23:57:34"
                        },
                        new
                        {
                            Id = new Guid("92d48d8c-0494-4350-afa1-342a720f3348"),
                            Amenity = "",
                            CreatedDateTime = "28-02-2024 23:57:34",
                            Details = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa2.jpg",
                            Name = "Diamond Pool Villa",
                            Occupancy = 4,
                            Rate = 600,
                            Sqft = 1100,
                            UpdatedDateTime = "28-02-2024 23:57:34"
                        });
                });

            modelBuilder.Entity("MagicVillaAPI.Models.DAO.VillaNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedDateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VillaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("villa_numbers");
                });

            modelBuilder.Entity("MagicVillaAPI.Models.DAO.VillaNumber", b =>
                {
                    b.HasOne("MagicVillaAPI.Models.DAO.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
