### PUT Request
curl --location --request PUT 'https://jsonplaceholder.typicode.com/posts/1' \
--header 'Content-Type: application/json' \
--data '{
           "id": 1,
           "title": "foo",
           "body": "bar",
           "userId": 1
         }'


